M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu24.04.1} date 2025-09-01T10:40:32-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-01T10:40:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
%
G90
G05
T1
X92.215Y-75.61
X99.215Y-75.61
M30
